fix-webpack-issue
rsksmart/utils pull request #5
Opened 2020-06-26 14:00 UTC by jonathansmirnoff

There is an issue when it is tried to build using webpack the site. Basically the problem is that the webpack configuration is up of date. So it has been updated and also the reference to `ethereumjs-wallet`.
This PR it is related to #4.

It is important to merge this PR because right now it is not possible to build the site.

2020-06-26 14:16 UTC, bernacodesido submitted a review, later dismissed

2020-06-26 14:39 UTC, bguiz requested changes
The webpack stuff looks good, but I would suggest avoiding latest in the version fields of package.json, because you will automatically inherit any breaking changes each time you do npm install.
It's best to specify exact version numbers, or version numbrrs preceded by ^ so that only some version changes are automatically allowed

2020-06-26 14:40 UTC, bguiz submitted a review, later dismissed

2020-06-26 14:44 UTC, jonathansmirnoff commented
@bguiz good catch. Thanks!
I am updating the PR with that consideration.

2020-06-26 18:00 UTC, bernacodesido approved these changes

2020-06-27 02:34 UTC, bguiz approved these changes
LGTM

2020-06-29 12:25 UTC, alepc253 approved these changes

2020-06-29 12:31 UTC, merged